import type { Entity } from './types'

export const mockEntities: Entity[] = [
  {
    id: 'ngo-1',
    kind: 'NGO',
    name: 'Sahyog Foundation',
    email: 'sahyog.ngo@example.org',
    phone: '+91 80412 34567',
    state: 'KA',
    city: 'Bengaluru',
    latitude: 12.9716,
    longitude: 77.5946,
    focus: ['SDG 4', 'SDG 8', 'SDG 10'],
    about:
      'Education-to-employment programs for underserved youth, with industry mentorship and skills bootcamps.',
    website: 'https://example.org/sahyog',
    resourcesOffered: ['Volunteer network', 'Community partners', 'Field survey teams'],
    resourcesNeeded: ['Internship partners', 'Scholarships', 'Cloud credits'],
  },
  {
    id: 'ngo-2',
    kind: 'NGO',
    name: 'Namma Neer Collective',
    email: 'neer.ngo@example.org',
    phone: '+91 44223 45678',
    state: 'TN',
    city: 'Chennai',
    latitude: 13.0827,
    longitude: 80.2707,
    focus: ['SDG 6', 'SDG 11', 'SDG 13'],
    about:
      'Urban water resilience: rainwater harvesting audits, lake restoration coordination, and citizen dashboards.',
    website: 'https://example.org/namma-neer',
    resourcesOffered: ['Ward-level data', 'Community mobilization', 'WASH expertise'],
    resourcesNeeded: ['IoT sensors', 'GIS support', 'CSR funding'],
  },
  {
    id: 'ngo-3',
    kind: 'NGO',
    name: 'Kerala Health Net',
    email: 'khn.ngo@example.org',
    phone: '+91 48431 23456',
    state: 'KL',
    city: 'Kochi',
    latitude: 9.9312,
    longitude: 76.2673,
    focus: ['SDG 3', 'SDG 5'],
    about:
      'Primary health outreach with maternal care programs and telemedicine facilitation for rural communities.',
    website: 'https://example.org/khn',
    resourcesOffered: ['Health camps', 'Frontline workers', 'Clinical partnerships'],
    resourcesNeeded: ['Telemedicine devices', 'Training content', 'Logistics support'],
  },
  {
    id: 'ngo-4',
    kind: 'NGO',
    name: 'Bengaluru Learning Mission',
    email: 'contact@blm.example.org',
    phone: '+91 80456 78901',
    state: 'KA',
    city: 'Bengaluru',
    latitude: 12.955,
    longitude: 77.62,
    focus: ['SDG 4', 'SDG 10'],
    about: 'After-school learning support and digital literacy for low-income neighborhoods.',
    website: 'https://example.org/blm',
    resourcesOffered: ['Community tutors', 'Learning centers', 'Digital curriculum'],
    resourcesNeeded: ['Laptops', 'Scholarship support'],
  },
  {
    id: 'ngo-5',
    kind: 'NGO',
    name: 'Mysuru Women Collective',
    email: 'hello@mwc.example.org',
    phone: '+91 82144 55667',
    state: 'KA',
    city: 'Mysuru',
    latitude: 12.2958,
    longitude: 76.6394,
    focus: ['SDG 5', 'SDG 8'],
    about: 'Women entrepreneurship network focused on skilling and market linkages.',
    website: 'https://example.org/mwc',
    resourcesOffered: ['SHG network', 'Skill trainers'],
    resourcesNeeded: ['Microfinance partners', 'Corporate buyers'],
  },
  {
    id: 'co-1',
    kind: 'COMPANY',
    name: 'CloudKaveri Technologies',
    email: 'partnerships@cloudkaveri.example.com',
    state: 'KA',
    city: 'Mysuru',
    focus: ['SDG 9', 'SDG 11', 'SDG 17'],
    about:
      'Cloud + API platform provider for civic tech and social impact. Offers credits and integration support.',
    website: 'https://example.com/cloudkaveri',
    resourcesOffered: ['Cloud credits', 'API integration', 'Engineering volunteers'],
    resourcesNeeded: ['Pilot partners', 'Impact use-cases'],
  },
  {
    id: 'co-2',
    kind: 'COMPANY',
    name: 'AgriNova Startups',
    email: 'hello@agrinova.example.com',
    state: 'AP',
    city: 'Vijayawada',
    focus: ['SDG 2', 'SDG 12', 'SDG 13'],
    about:
      'Agri advisory + supply chain transparency for smallholder farmers. Interested in field pilots with NGOs.',
    website: 'https://example.com/agrinova',
    resourcesOffered: ['Advisory app', 'Soil testing partners', 'Pilot budget'],
    resourcesNeeded: ['Farmer communities', 'Training partners'],
  },
  {
    id: 'co-3',
    kind: 'COMPANY',
    name: 'SunGrid Energy',
    email: 'csr@sungrid.example.com',
    state: 'TG',
    city: 'Hyderabad',
    focus: ['SDG 7', 'SDG 8', 'SDG 13'],
    about:
      'Renewable energy company running CSR microgrid and green jobs programs across South India.',
    website: 'https://example.com/sungrid',
    resourcesOffered: ['CSR grants', 'Solar microgrids', 'Green jobs training'],
    resourcesNeeded: ['Community sites', 'Maintenance partners'],
  },
  {
    id: 'co-4',
    kind: 'COMPANY',
    name: 'Bengaluru Data Systems',
    email: 'partners@bds.example.com',
    state: 'KA',
    city: 'Bengaluru',
    focus: ['SDG 9', 'SDG 17'],
    about: 'Data platform startup supporting social impact monitoring and analytics.',
    website: 'https://example.com/bds',
    resourcesOffered: ['Data dashboards', 'API support'],
    resourcesNeeded: ['Field deployment partners'],
  },
  {
    id: 'co-5',
    kind: 'COMPANY',
    name: 'Mysuru Renew Labs',
    email: 'csr@mrl.example.com',
    state: 'KA',
    city: 'Mysuru',
    focus: ['SDG 7', 'SDG 13'],
    about: 'Clean energy pilots and energy-efficiency advisory for communities.',
    website: 'https://example.com/mrl',
    resourcesOffered: ['Solar kits', 'Technical experts'],
    resourcesNeeded: ['Pilot sites', 'Training partners'],
  },
]

